### ISSUE TITLE
Is turning dicts in to Dicts unwanted behaviour?

### ISSUE THREAD

**Issue by mewwts** [mewwts/addict#29]
Some people have over the weekend expressed their concern that the fact that we are not keeping the original dict-object, merely a Dict-clone of it, in our Dict, might be dangerous. In situations where you do 
```Python
>>> something = {'a': [1, 2, 3]}
>>> a  = Dict(something)
>>> something['a'].append(4)
>>> a
 {'a': [1, 2, 3]}
>>> something
 {'a': [1, 2, 3, 4]}
```
I completely understand this concern. Perhaps Dict.__init__ may have a parameter to control this behaviour, during construction. And then we remove this for dicts that are added not through Dict.__init__. Something in the lines of:

```Python
>>> a = Dict({'b': {'c': 2}}, addicted=True)
>>> a.b.d = {'e': 3}
>>> a
{'b': {'c': 2, 'd': {'e': 3}}}
>>> a.b.d.f = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't set attributes of built-in/extension type 'dict'
```

**Comment by sbillaudelle** [comment]
The current behavior definitely does not comply with Python's default handling of mutable objects and is not consistent in itself!

However, I would not say that this is an issue of turning ```dict``` instances into ```Dict```s. The problem lies in the special handling of ```list``` objects. The following example is – as far as Python's data handling is concerned – identical to the above use case:

```python
>>> class Foo: pass
>>> something = {'a': Foo()}
>>> a = Dict(something)
>>> something['a'].child = 42
>>> a.a.child
42
>>> something['a'].child
42
```

In this case, ```a.a``` indeed is a "reference" to ```something['a']```, other than in the ```list``` example given above.

In my personal opinion, lists should not be copied when setting them as a value of a ```Dict``` instance but should be handled the same way as regular mutable objects.

Returning to the original question, I would say that standard ```dict``` instances should be converted to ```Dict```s. In my opinion, this follows the idea of this project, to enable quick and sleek access to a ```dict```s children.

Making this a user's choice – e.g. via a parameter in the ```__init__``` function – is definitely a good compromise, even if this would lead to an increased workload for maintaining this module.

(Just a quick note: While I have the feeling to have some idea about Python's data model and mutable/immutable stuff, the matter is not that trivial. I might be wrong about some of my statements above.)

**Comment by mewwts** [comment]
Thanks @sbillaudelle.

The fact that lists are being copied right now is a result of recursively (even inside lists) turning dicts into addicts, leaving the following behaviour
```Python
>>> a_dict = Dict()
>>> my_list = [{'a': 2}]
>>> a_dict.b = my_list
>>> a_dict.b[0].a
2
```
but indeed also clones the list
```Python
>>> a_dict.b.append(2)
>>> a_dict
{'b': [{'a': 2}, 2]}
>>> my_list
[{'a': 2}]
>>> 
```
Is it better if we keep a reference to the same list inside the ```Dict```, but turn the elements that are dictionaries into ```Dict```s?
```Python
>>> a_dict = Dict()
>>> my_list = [{'a': 2}]
>>> isinstance(my_list[0], Dict)
False
>>> a_dict.b = my_list
>>> isinstance(my_list[0], Dict)
True
```

I think I prefer the latter, although it might seem hazardous to mess with users data. But this is indeed what we do with dictionaries being put into a ```Dict```.

So I guess this boils down to, if we've decided to not clone lists;
If you put a list of stuff into an addict, should we iterate through them and convert dictionaries to Dicts, modifying the data that you put in? (

**Comment by rocktavious** [comment]
Sorry just learning about this library and loving it.  I think to keep this class as similar to a python dict's functionality would be ideal.  as seen here i would think as it currently stands this is a this is a bug that needs to be fixed, because doing the exact same example as originally above with just python dict's you get this...

    >>> something = {"a": [1,2,3]}
    >>> a = dict(something)
    >>> something["a"].append(4)
    >>> a
    {'a': [1, 2, 3, 4]}
    >>> something
    {'a': [1, 2, 3, 4]}

And just for futher show this with standard python objects in a deeper recursion...

    >>> something = {"a":[1,2,{"b":[1,2,3]}]}
    >>> a = dict(something)
    >>> something["a"][2]["b"].append(4)
    >>> a
    {'a': [1, 2, {'b': [1, 2, 3, 4]}]}
    >>> something
    {'a': [1, 2, {'b': [1, 2, 3, 4]}]}

So IMO this should be fixed.

**Comment by mewwts** [comment]
Hey @rocktavious. 

I agree that `addict` differs from the builtin `dict` class on this. The thought was to allow the second example to be written something along the lines of
```
>>> something = {"a":[1,2,{"b":[1,2,3]}]}
>>> a = Dict(something)
>>> something.a[2].b.append(4)
>>> something
{'a': [1, 2, {'b': [1, 2, 3, 4]}]}
```
But in order to enable that syntax for both lists and tuples, they are being clones such that the original list will be left intact:
```
>>> a
{'a': [1, 2, {'b': [1, 2, 3]}]}
```
I thought perhaps we could disable cloning by default, but be able to turn it on by introducing an argument that enables cloning. I'll think about it, and perhaps implement it tonight. Thanks for commenting and using! :+1: Any further thoughts?

**Comment by rocktavious** [comment]
The only thing i would be careful about is if cloning defaults to False, then wouldn't dictionaries inside lists not become addict's so the following would error

    >>> something = {"a":[1,2,{"b":[1,2,3]}]}
    >>> a = Dict(something)
    >>> something.a[2].b

Would raise an "Attribute Error" because there is no attribute "b" on the dictionary at something.a[2]

**Comment by mewwts** [comment]
I've given this some more thought and I actually think we need to land on a behaviour without introducing more complexity (i.e. a parameter). Imho, we have two choices. Either the values we set are being cloned (and `dict`s turned into `addict`s) like today, or the values set are not being cloned. 

I'm not sure, but I do think the constructor is fine the way it is: turning `dicts` into `addict`s, and cloning lists and tuples. Here it should be clear that we're making a new object.

However, when values are set outside the constructor, i.e.
```
 
```
