### ISSUE TITLE
Optionally based on OrderedDict

### ISSUE THREAD

**Issue by joslarson** [mewwts/addict#57]
I'm thinking it would be nice to be able to use this with OrderedDict, such that the order things were put into the dict is the same order they come out when dumped to json for an api endpoint.

Maybe something like the following where

```py
import json
from addict import Dict
...
response = Dict(ordered=True)
response.count = len(results)
response.next = next_url
response.prev = prev_url
response.results = results

print(json.dumps(response))
```

prints the following in order:

```json
{
    "count": 435,
    "next": "/.../?page=2",
    "prev": null,
    "results": [
        ...
    ]
}
```

Thoughts?

**Comment by mewwts** [comment]
Hey, @joslarson. Thanks for reaching out!

It's been a while since I actively maintained this project, but I'd like to get on the horse again. I'm thinking of how to make this the most flexible. The current implementation makes it a bit of an hassle to make this kind of stuff possible.

Do you have any ideas on how to make such a change? 

I'll schedule some time soon to have a look Addict.

Cheers 😊

**Comment by joslarson** [comment]
Thanks for the response, I'm definitely willing to help out, but I haven't dug into the source yet as I wanted to talk about it at a conceptual level first. Since posting this I've been thinking that with this project it might make more sense to just base it on OrderedDict by default. I'm not sure if the OrderedDict is less performant or not, but I don't think that should matter in a library whose goal is to make the ultimate flexible dictionary. I'm not even convinced you'd need to have the option for an unordered base.

**Comment by mewwts** [comment]
Hi @joslarson, I've decided to close this as I've decided to keep the module leaner instead of adding more functionality. 🎱
