### ISSUE TITLE
Assigning to element of array does not make dicts get wrapped

### ISSUE THREAD

**Issue by domdom** [mewwts/addict#67]
I've already made a PR for this, apologies if this is excessive. I would like to be able to assign dicts to parts of arrays and still have the dicts wrapped by addict.
```python
p = Dict()
p.a = [{'b':'works'}]
print (p.a[0].b) # b
p.a[0] = {'b':'does not work'}
print (p.a[0].b) # raises exception
```

**Comment by mewwts** [comment]
Hi @domdom, thanks for this!

This was actually the behaviour before 1.0.0, and I deprecated it because I decided modifying objects was not a safe thing to do. Currently, I'd advice you to use addict dictionaries where you need this sort of behaviour. I.e. writing out `p.a = [Dict({'b': 'works'})]`.

If you're getting a `dict` from a different library, it should be sufficient to wrap the `dict` in a call to `Dict` to obtain the behavoiur: `Dict(returned_dict_from_somewhere)`.

**Comment by domdom** [comment]
Hrm, what is unsafe about it? I imagine it is the fact that tuples and lists get duplicated each time they are hooked?

**Comment by mewwts** [comment]
You're right - addict is a data structure. It's not exactly the fact that things get duplicated, but the fact that, if we do the above, we clone objects and discard the originals. Hence, the reference to the object is lost. This still happens with addicts constructor as of today, but I'm leaning more towards taking it away entirely, than extending it.

```
>>> a = [1, 2, 3]
>>> addict_dict = Dict({'a': a})
>>> normal_dict = dict({'a': a})
>>> addict_dict.['a'][2] = 4
>>> a
[1, 2, 3]
>>> normal_dict['a'][2] = 4
>>> a
[1, 2, 4]
```

**Comment by domdom** [comment]
Ahh yes. I agree with your assessment. I am happy to close this issue :). 

And thanks for explaining that by the way, for my particular use case I can accept those consequences; but even so, I was unsure of the implications since I do not grok this all as well as you do :P.

**Comment by mewwts** [comment]
Great! In any case I want to thank you for fiddling about with `addict`!
