### ISSUE TITLE
Read Only version

### ISSUE THREAD

**Issue by zee-sh** [mewwts/addict#74]
How can I make this read-only and when you try to add an attribute it will raise an exception, something like a Frozen Addict.

Also why does this create an empty dict on when trying to access an attribute that does not exist. It should raise an exception unless you are setting an attribute that does not exist

**Comment by Ohjeah** [comment]
Had the same issue.
This works for me:

https://gist.github.com/Ohjeah/41b103e4bc15452af5bbc89747962369

**Comment by mewwts** [comment]
Hey! 

Unfortunately, it's (afaik) not possible to get `addict`s functionality without creating an empty dictionary on lookup. Essentially, when you do `my_dict.a.b = 2`, Python first tries to figure out what `my_dict.a.b` is. If `my_dict.a` does not exist when `__getattr__` is called on `my_dict`, Python will raise an exception. Hence, as a workaround, and tbh this is the whole idea that makes `addict` work, we return a empty dictionary, so that when the `__setattr__` is called on `my_dict.a` we're able to do set the item in `my_dict`.

If I'm not misunderstanding the question you could always call `.to_dict()` in order to transform it into a regular python `dict`, and disallow further `__setattr__`. 

Cheers,

Mats

**Comment by Ohjeah** [comment]
If you just use `.to_dict()` you will lose the dot-access to dict items too!

**Comment by mewwts** [comment]
That's true @Ohjeah.

**Comment by Ohjeah** [comment]
Hence the LockedDict (see the gist). It serves as a read only version of addict.Dict. Works well for me if I want an exception rather a None value return on a failed item lookup.
